[package]
name = "bro-ocr"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.9", features = ["derive"] }
reqwest = { version = "0.12.5", features = ["blocking", "json"] }

[dev-dependencies]
anyhow = "1.0.86"

